@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.elenterius.blightlings.network;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;