# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47.1.3,)
loader_version_range=[47,)

## Mappings
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

## Mixin Extras (remove in 1.21)
mixin_extras_version=0.5.0
mixin_extras_version_range=[0.4.1,)

# Biomancy Mod Properties
mod_id=biomancy
mod_name=Biomancy
mod_license=MIT & CC-BY-NC-4.0
mod_major_version=2
mod_semantic_version=9.9.0-alpha.0
mod_group_id=com.github.elenterius
mod_vendor=Elenterius
mod_authors=Elenterius, RhinoW
mod_credits=The Shroome, kd8lvt, Shorepion, lordketer, Tarnisheart, Kitteh6660, Jasdan, ZeoMaddox, ItsLumine, RuskieThe3rd, M4rc3ll0 and many more people from the Biomancy Discord.
mod_description=Biopunk and Flesh Magic inspired tech-magic mod that has a fleshy art theme.
mod_url=https://modrinth.com/mod/biomancy
mod_issue_url=https://github.com/Elenterius/Biomancy/issues
mod_update_url=https://api.modrinth.com/updates/uAAuyU4M/forge_updates.json

# Dependencies

## Geckolib Mod
geckolib_version=4.7.1.1
geckolib_version_range=[4.7,)

## Modonomicon
modonomicon_version=1.77.0

## Just Enough Items (JEI) Mod
jei_version=15.2.0.27
jei_version_range=[15.2.0,)