@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.creativechasm.blightlings.init;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;