# The overall format is standard TOML format, v0.5.0.
modLoader = "javafml"
loaderVersion = "[39,)" #This is typically bumped every Minecraft version by Forge
license = "MIT"
issueTrackerURL = "https://github.com/Elenterius/Biomancy/issues" #optional
updateJSONURL = "https://github.com/Elenterius/Biomancy/blob/main/update.json?raw=true"
showAsResourcePack = false

[[mods]]
modId = "biomancy"
version = "${file.jarVersion}"
displayName = "Biomancy"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/biomancy" #optional
logoFile = "text_logo.png" #optional
logoBlur = false
credits = "I grateful to thank RhinoW for their artwork and game design help. Selea for feeback and help"
authors = "Elenterius, RhinoW"
description = '''Biopunk and Flesh Magic inspired tech-magic mod that has a fleshy art theme.'''

[[dependencies.biomancy]]
modId = "combat_commons"
mandatory = true
versionRange = "[0.2.0-beta,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.biomancy]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH" # BOTH, CLIENT or SERVER

[[dependencies.biomancy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"
