# The overall format is standard TOML format, v0.5.0.
modLoader = "javafml"
loaderVersion = "[40,)" #This is typically bumped every Minecraft version by Forge
license = "MIT"
issueTrackerURL = "https://github.com/Elenterius/Biomancy/issues" #optional
showAsResourcePack = false

[[mods]]
modId = "biomancy"
version = "${file.jarVersion}"
displayName = "Biomancy"
updateJSONURL = "https://github.com/Elenterius/Biomancy/blob/main/update.json?raw=true"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/biomancy" #optional
logoFile = "text_logo_pixel.png" #optional
logoBlur = false
credits = "RhinoW for artwork and game design help. Shorepion for sound desing and music. Selea for general feeback and help with version 1.0"
authors = "\u00A72Elenterius\u00A7r, \u00A76RhinoW\u00A7r, \u00A75Shorepion"
description = '''Biopunk and Flesh Magic inspired tech-magic mod that has a fleshy art theme.'''

[[dependencies.biomancy]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.11,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.biomancy]]
modId = "forge"
mandatory = true
versionRange = "[40.1.34,)"
ordering = "NONE"
side = "BOTH" # BOTH, CLIENT or SERVER

[[dependencies.biomancy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
