# The overall format is standard TOML format, v0.5.0.
modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
issueTrackerURL = "https://github.com/Elenterius/Biomancy/issues" #optional

[[mods]] #mandatory
modId = "biomancy" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Biomancy" #mandatory
displayURL = "https://github.com/Elenterius/Biomancy" #optional
logoFile = "logo.png" #optional
credits = "Lorc (https://lorcblog.blogspot.com/) for icons which are under CC BY 3.0 (http://creativecommons.org/licenses/by/3.0/) and were modified by downscaling and recoloring."
authors = "Elenterius" #optional
#mandatory
description = '''
A Mod about creating life from meat and flesh.
'''

[[dependencies.biomancy]] #optional
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH" # BOTH, CLIENT or SERVER

[[dependencies.biomancy]]
modId="minecraft"
mandatory = true
versionRange = "[1.16.3,1.17)"
ordering = "NONE"
side="BOTH"
