modLoader = "javafml"
loaderVersion = "[43,)" #This is typically bumped every Minecraft version by Forge
license = "MIT & CC-BY-NC-4.0"
issueTrackerURL = "https://github.com/Elenterius/Biomancy/issues" #optional
showAsResourcePack = false

[[mods]]
modId = "biomancy"
version = "${file.jarVersion}"
displayName = "Biomancy 2"
updateJSONURL = "https://api.modrinth.com/updates/uAAuyU4M/forge_updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/biomancy" #optional
logoFile = "text_logo_small.png" #optional
logoBlur = false
credits = "RhinoW for artwork and game design help. Shorepion for sound design and music."
authors = "\u00A72Elenterius\u00A7r, \u00A76RhinoW\u00A7r, \u00A75Shorepion"
description = '''Biopunk and Flesh Magic inspired tech-magic mod that has a fleshy art theme.'''

[[dependencies.biomancy]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.1.39,4.0)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.biomancy]]
modId = "jei"
mandatory = false
versionRange = "[11.5.0,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.biomancy]]
modId = "forge"
mandatory = true
versionRange = "[43.2.0,)"
ordering = "NONE"
side = "BOTH" # BOTH, CLIENT or SERVER

[[dependencies.biomancy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"
