# The overall format is standard TOML format, v0.5.0.
modLoader = "javafml" #mandatory
loaderVersion = "[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "MIT"
issueTrackerURL = "https://github.com/Elenterius/Blightlings/issues" #optional

[[mods]] #mandatory
modId = "blightlings" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Blightlings" #mandatory
displayURL = "https://github.com/Elenterius/Blightlings" #optional
logoFile = "logo.png" #optional
credits = "" #optional
authors = "Elenterius" #optional
#mandatory
description = '''
Mod that adds Arthropods and obscure artifacts with a blight theme.
'''

[[dependencies.blightlings]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[35,)" #mandatory
ordering = "NONE" # BEFORE or AFTER required if the relationship is not mandatory
side = "BOTH" # BOTH, CLIENT or SERVER

[[dependencies.blightlings]]
    modId="minecraft"
mandatory = true
versionRange = "[1.16.4]"
ordering = "NONE"
    side="BOTH"
