modLoader = "javafml"
loaderVersion = "[40,)" #This is typically bumped every Minecraft version by Forge
license = "MIT & CC-BY-NC-4.0"
issueTrackerURL = "https://github.com/Elenterius/Biomancy/issues" #optional
showAsResourcePack = false

[[mods]]
modId = "biomancy"
version = "${file.jarVersion}"
displayName = "Biomancy 2"
updateJSONURL = "https://api.modrinth.com/updates/uAAuyU4M/forge_updates.json"
displayURL = "https://modrinth.com/mod/biomancy" #optional
logoFile = "text_logo_small.png" #optional
logoBlur = false
credits = "\u00A77RhinoW, The Shroome, Shorepion, Kitteh6660, ZeoMaddox, ItsLumine, RuskieThe3rd, M4rc3ll0"
authors = "\u00A72Elenterius\u00A7r, \u00A76RhinoW\u00A7r"
description = '''ยง7Biopunk and Flesh Magic inspired tech-magic mod that has a fleshy art theme.'''

[[dependencies.biomancy]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.54,4.0)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.biomancy]]
modId = "jei"
mandatory = false
versionRange = "[9.7.0,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.biomancy]]
modId = "forge"
mandatory = true
versionRange = "[40.1.80,)"
ordering = "NONE"
side = "BOTH" # BOTH, CLIENT or SERVER

[[dependencies.biomancy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
