# The overall format is standard TOML format, v0.5.0.
modLoader = "javafml"
loaderVersion = "[36,)" #This is typically bumped every Minecraft version by Forge
license = "MIT"
issueTrackerURL = "https://github.com/Elenterius/Biomancy/issues" #optional
showAsResourcePack = false

[[mods]]
modId = "biomancy"
version = "${file.jarVersion}"
displayName = "Biomancy"
displayURL = "https://github.com/Elenterius/Biomancy" #optional
logoFile = "text_logo.png" #optional
logoBlur = false
credits = "I thank GPT-Neo 1.3B for writting support ;)"
authors = "Elenterius" #optional
description = '''Biomancy is a Biopunk inspired Mod and themed around flesh magic and bio-manipulation.'''

[[dependencies.biomancy]] #optional
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH" # BOTH, CLIENT or SERVER

[[dependencies.biomancy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,1.17)"
ordering = "NONE"
side = "BOTH"
