@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.elenterius.blightlings.statuseffect;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;