blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://discord.gg/424awTDdJJ
    about: Share your ideas for this project
  - name: Need Help?
    url: https://discord.gg/424awTDdJJ
    about: Ask questions you’re wondering about
