blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/Elenterius/Biomancy/discussions/new?category=ideas
    about: Share your ideas for this project
  - name: Need Help?
    url: https://github.com/Elenterius/Biomancy/discussions/new?category=help
    about: Ask questions you’re wondering about
