@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.elenterius.blightlings.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;