@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.elenterius.blightlings.handler;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;