@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.creativechasm.blightlings.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;