@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.elenterius.blightlings.world;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;