# On a github release this workflow will build the Mod with Gradle and cache/restore any dependencies to improve the workflow execution time
# Note: cache writing only happens on the default branch but child branches do have read access to the default branch

name: Build Mod Artifact

on:
  release:
    types: [published]

jobs:
  build-mod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.2.2
    
    - name: Generate Assets
      uses: gradle/gradle-build-action@v2.2.2
      with:
        arguments: runDataCI

    - name: Build Artifact
      uses: gradle/gradle-build-action@v2.2.2
      with:
        arguments: build

#    - name: Upload Artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: artifacts
#        path: build/libs

    - name: Upload Artifact to Github Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: build/libs/*