name: Cache Oxipng

on:
  workflow_dispatch:
  workflow_call:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  cache:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Cargo Install Oxipng
      uses: baptiste0928/cargo-install@v1.3.0 #provides cache-efficient Rust crates installation
      with:
        crate: oxipng
