name: Cache Gradle

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cache:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Setup Mod Development Kit
        uses: gradle/gradle-build-action@v2.2.2
        with:
          arguments: build # build is called to properly setup the minecraft mod development environment
