# This is a basic workflow to help you get started with Actions

name: Github Release

on:
  workflow_dispatch:

jobs:
  cache-gradle:
    uses: elenterius/biomancy/.github/workflows/cache_gradle.yml@main
  cache-oxipng:
    uses: elenterius/biomancy/.github/workflows/cache_oxipng.yml@main
      
  create-release:
    needs: [cache-gradle, cache-oxipng]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            version-file: './mod_version.json'
            version-path: 'semantic'
            output-file: 'false'
            git-message: 'chore(release): {version}'
            tag-prefix: 'v2.'

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
