# This is a basic workflow to help you get started with Actions

name: Github Release

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            output-file: "false"
            git-message: 'chore(release): {version}'
            tag-prefix: 'v2.'
            git-branch: 'main'

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: "true"
