name: Test Mod Build on PR

on:
  pull_request:
    branches:
      - '**/prod'
      - '**/dev'

jobs:
  test_pull_request:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test Asset Generation
        uses: gradle/gradle-build-action@v2
        with:
          arguments: runData

      - name: Test Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build